version: "3.9"
services:
  prometheus:
    image: prom/prometheus:v2.27.1
    volumes:
      - ./prometheus:/etc/prometheus/
      - data-prometheus:/prometheus
    ports:
      - 9091:9090

  grafana:
    image: grafana/grafana:7.5.7
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    environment:
    - "GF_INSTALL_PLUGINS=pyroscope-datasource,pyroscope-panel"
    ports:
      - 3000:3000

  pyroscope:
    image: "pyroscope/pyroscope:latest"
    ports:
      - 4040:4040
    command:
      - server
    environment:
      - PYROSCOPE_LOG_LEVEL=info
      - PYROSCOPE_WAIT_AFTER_STOP=true

volumes:
  data-prometheus:
    driver: local
